sudo: required
language: bash
services:
  - docker

matrix:
  include:
    - env: TAG=martialblog/limesurvey-apache
      script: cd 3.0/apache; docker build -q -t $TAG . && cd ../..; ./tests/run.sh $TAG
    - env: TAG=martialblog/limesurvey-fpm
      script: cd 3.0/fpm; docker build -q -t $TAG . && cd ../..; ./tests/run.sh $TAG
    - env: TAG=martialblog/limesurvey-alpine
      script: cd 3.0/fpm; docker build -q -t $TAG . && cd ../..; ./tests/run.sh $TAG
