sudo: required
language: bash
services:
  - docker

matrix:
  include:
    - env: TAG=martialblog/limesurvey-apache
      script: docker build -q -t $TAG -f apache/Dockerfile . && tests/run.sh $TAG
    - env: TAG=martialblog/limesurvey-fpm
      script: docker build -q -t $TAG -f fpm/Dockerfile . && tests/run.sh $TAG
