version: "3.0"
services:
  limesurvey:
    build:
      context: .
      dockerfile: apache/Dockerfile
    links:
      - lime-db
    depends_on:
      - lime-db
    ports:
      - "8080:80"
  lime-db:
    image: mysql:5.7
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
